### ISSUE TITLE
[Proposal] Create 3 Groups from Parallel Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1446] opened 2023-03-03 19:20 UTC
A [Parallel Identity Token](https://developer.parallelmarkets.com/docs/token/) is a non-transferrable ERC-721 NFT that is the on-chain representation of an off-chain KYC, accreditation and international sanctions verification.

Creating the Parallel Identity Token Group will enable to generate new sybil-resistant Groups from members that are unique humans verified by a KYC, accredited investors and safe from sanctions.

### Specifications

Expected Group n°1: list of all addresses holding a Parallel Identity Token.

Expected Group n°2: list of all addresses holding a Parallel Identity Token and verified as accredited investors. 

Expected Group n°3: list of all addresses holding a Parallel Identity Token and verified as safe from international sanctions. 

### Tips on how to create the Group

Parallel Identity Token is minted on Ethereum with [this](https://etherscan.io/token/0x9ec6232742b6068ce733645af16ba277fa412b0a) contract address.

Group n°1: the easiest way to extract the list of addresses is by using BigQuery.

Group n°2 & Group n°3: you can use their [on-chain data](https://developer.parallelmarkets.com/docs/token/) or [API](https://developer.parallelmarkets.com/docs/server/accreditations-api) to verify the status.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by sampolgar** [comment] 2023-04-18 13:21
Group 1. We can easily find the list of parallel holders via BigQuery
Group 2. & Group 3. without the parallel API (which requires an admin account), we could use Alchemy to query their endpoints.
1. query to getNFTsForCollection - this returns all tokens and their metadata (will need paging)
2. query to getOwnersForCollection - this returns all owners
3. we would need to match 1 and 2 

Result of 1) would return an array of objects like below with tokenId and metadata
```
{
      "contract": {
        "address": "0x9ec6232742b6068ce733645af16ba277fa412b0a"
      },
      "id": {
        "tokenId": "0x0000000000000000000000000000000000000000000000000000000000000065",
        "tokenMetadata": {
          "tokenType": "ERC721"
        }
      },
      "title": "Parallel Identity (PID) Token",
      "description": "The [Parallel Identity (PID) Token](https://parallelmarkets.com/web3) is a non-transferrable NFT that links a real-world individual or business identity with a wallet. The PID Token provides Know Your Customer (KYC), international sanctions monitoring, and accreditation determination for all token holders.",
      "tokenUri": {
        "gateway": "https://alchemy.mypinata.cloud/ipfs/QmbdypcHV5DmgPhSfMf78XeuJWz2TtiY8p6APc1BvhR31e",
        "raw": "ipfs://QmbdypcHV5DmgPhSfMf78XeuJWz2TtiY8p6APc1BvhR31e"
      },
      "media": [
        {
          "gateway": "https://nft-cdn.alchemy.com/eth-mainnet/e858a42861537c9db03b74d3a2313bc9",
          "thumbnail": "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/e858a42861537c9db03b74d3a2313bc9",
          "raw": "ipfs://QmexUqNW4jqkWTFJCJavDFQHZHuoBYZP7sakGHu3VFv93X",
          "format": "png",
          "bytes": 300024
        }
      ],
      "metadata": {
        "image": "ipfs://QmexUqNW4jqkWTFJCJavDFQHZHuoBYZP7sakGHu3VFv93X",
        "external_url": "https://parallelmarkets.com/web3",
        "animation_url": "ipfs://Qmew24oAVM7Lu6h3YqoX8oTPFLYymaQL7jJLeFrPsp4hw6",
        "background_color": "032346",
        "name": "Parallel Identity (PID) Token",
        "description": "The [Parallel Identity (PID) Token](https://parallelmarkets.com/web3) is a non-transferrable NFT that links a real-world individual or business identity with a wallet. The PID Token provides Know Your Customer (KYC), international sanctions monitoring, and accreditation determination for all token holders.",
        "attributes": [
          {
            "value": "Yes",
            "trait_type": "KYC/AML Complete"
          },
          {
            "value": "Individual",
            "trait_type": "Token Holder"
          }
        ]
      },
      "timeLastUpdated": "2023-04-08T03:03:06.835Z",
      "contractMetadata": {
        "name": "ParallelID",
        "symbol": "PID",
        "totalSupply": "144",
        "tokenType": "ERC721",
        "contractDeployer": "0x11a5b37a6ed48f22b9039067edd89f549c3bfd02",
        "deployedBlockNumber": 14903535,
        "openSea": {
          "floorPrice": 0,
          "collectionName": "ParallelID",
          "safelistRequestStatus": "not_requested",
          "lastIngestedAt": "2023-03-20T21:48:04.000Z"
        }
      }
    },
```

result of 2) would return array of owners and tokenId's to match with 1)
```
    {
      "ownerAddress": "0x00000000051cbce3fd04148cce2c0adc7c651829",
      "tokenBalances": [
        {
          "tokenId": "0x0000000000000000000000000000000000000000000000000000000000000064",
          "balance": 1
        }
      ]
    },
    {
      "ownerAddress": "0x060fcdd22e1ae6b45d01978d322075a7ff0e6a07",
      "tokenBalances": [
        {
          "tokenId": "0x0000000000000000000000000000000000000000000000000000000000000046",
          "balance": 1
        }
      ]
    },
```

Does that sound ok? @MartinGbz

**Comment by MartinGbz** [comment] 2023-04-20 13:55
Hey @sampolgar if with 1) we succeed to know of this particular token Id is "accredited investors" or "safe from sanctions" I think it's ok to do like this.

From what I see on etherscan/opensea "accredited investors" seems to be a trait of the NFT => so for this one you can use your method (and you will see in the "attributes" field of the 1) return).

But for the "safe from sanctions" you need to call the isSanctionsSafe (or isSanctionsSafeIn or isSanctionsMonitores, I didn't go further to know which one to use) function of the NFT contract. => so for this, maybe use the jsonRPCProvider to call this function, but the problem is that you will have to loop on all tokenId in order to fetch each isSanctionsSafe state. I'm not sure this solution is really scalable, but for now there are not that much NFT. We have to try this way I think.

**Comment by sampolgar** [comment] 2023-05-21 11:42
Going through final testing on this https://github.com/sampolgar/sismo-hub/tree/group-parallel-identity

**Comment by MartinGbz** [comment] 2023-06-07 16:41
Thanks for your contribution again @sampolgar !
The PR has been merged here: https://github.com/sismo-core/sismo-hub/pull/1858 ✅

**Closed by MartinGbz** 2023-06-07 16:41 UTC
Labels: Group Creation
